## Numpy
Numpy is used for scientific computing.It provides data structures and functions which are efficint in doing numerical computations.  
Numpy consits of different sub-modules tacking different sets of computations,like:core,lib,linalg, fft etc.  
Numpy has two fundamental objects, ndarray and ufunc.  
**ndarray** stands for n-dimensional array, which in turn is a collection of **same data type**.  
The reason we need arrays is because vectors, matrices and tensors , all are programatically represented as arrays.


In [1]:
import numpy as np

In [2]:
random_x = np.random.random()
print(random_x)
print(type(random_x))

0.7597295849471413
<class 'float'>


In [54]:
random_sqrt = np.sqrt(random_x)
print(random_sqrt.ndim)

0


In [4]:
random_power = np.power(random_x,random_sqrt)
print(random_power)

0.787008590209


In [5]:
array = np.random.random(3)
print(array)

[ 0.32487712  0.28843253  0.90841025]


In [53]:
array2 = np.array([1,2,3,4])
print(array2)
print(array2.ndim)

[1 2 3 4]
1


In [7]:
matrix = np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


Note that the level of nesting is the number of dimensions.

In [8]:
print(type(matrix))
print(matrix.dtype)
print(matrix.shape)

<class 'numpy.ndarray'>
int64
(2, 2)


Note that the level of nesting is the number of dimensions.

In [9]:
print(matrix.ndim)

2


In [10]:
print(np.sin(matrix))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


#### Row-major and column-major order
https://en.wikipedia.org/wiki/Row-_and_column-major_order

#### Chaining of functions

In [11]:
X = np.arange(20).reshape((4,5))
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


#### Exercise1:
Create a 3-dimensional nd-array cube Y, with 5 rows with 3 columns each and 2 faces. Record the output for Y[1][2][2].

In [63]:
#### Solution Exercise1
Y = np.arange(30).reshape((2,5,3))
print(Y)
print(Y.ndim)
print(Y.shape)
print(Y[1][2][2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
3
(2, 5, 3)
23


In [13]:
print("===== A ====")
a=np.array([1,2,3])
print(a)
print("dimensions:",str(a.ndim))
print("shape:",str(a.shape))
print("===== B ====")
b=np.array([a, a])
print(b)
print("dimensions:",str(b.ndim))
print("shape:",str(b.shape))
c=np.array([b,b])
print("===== C ====")
print(c)
print("dimensions:",str(c.ndim))
print("shape:",str(c.shape))
d=np.array([[[1,2],[1,2,3]]])
print("===== D ====")
print(d)
print("dimensions:",str(d.ndim))
print("shape:",str(d.shape))

===== A ====
[1 2 3]
dimensions: 1
shape: (3,)
===== B ====
[[1 2 3]
 [1 2 3]]
dimensions: 2
shape: (2, 3)
===== C ====
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
dimensions: 3
shape: (2, 2, 3)
===== D ====
[[[1, 2] [1, 2, 3]]]
dimensions: 2
shape: (1, 2)


#### Array Indexing and slicing:

The general notation for slicing is:  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    a[start:end]  
where start is the begining of a slice and end is the end of the slice where the element at index is not included in slice.

In [14]:
x = np.array([0,1,2,3,4,5,6])
print(x[:])    ## All the elements
print(x[1])    ## The second element
print(x[2:])   ## Everything from the third element
print(x[:2])   ## Everything till the third element
print(x[::2])   ## Every 2nd element
print(x[1:2])  ## Everything from second till the third element

[0 1 2 3 4 5 6]
1
[2 3 4 5 6]
[0 1]
[0 2 4 6]
[1]


Let's check the slicing and dicing in two dimensions:

In [15]:
x2=np.array([[1,2],[3,4],[5,6],[7,8]])
print(x2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
print("(x2[:] = ",x2[:])
print("(x2[1] = ",x2[1])
print("(x2[1,1] = ",x2[1,1])
print("(x2[:,1] = ",x2[:,1])
print("(x2[::2] = ",x2[::2,:])
print("(x2[1,:] = ",x2[1,:])
print("(x2[1:2,1:2] = ",x2[1:2,1:2])

(x2[:] =  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(x2[1] =  [3 4]
(x2[1,1] =  4
(x2[:,1] =  [2 4 6 8]
(x2[::2] =  [[1 2]
 [5 6]]
(x2[1,:] =  [3 4]
(x2[1:2,1:2] =  [[4]]


#### Numpy Data Types
Numpy has wider set of data types than core python. Numpy has a dtype class which handles the representation of a data type. 

In [17]:
print(x.dtype)

int64


In [18]:
print(x.dtype.type)
#https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html

<class 'numpy.int64'>


Data type	Description  
bool_	Boolean (True or False) stored as a byte   
int_	Default integer type (same as C long; normally either int64 or int32)  
intc	Identical to C int (normally int32 or int64)  
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)  
int8	Byte (-128 to 127)  
int16	Integer (-32768 to 32767)  
int32	Integer (-2147483648 to 2147483647)  
int64	Integer (-9223372036854775808 to 9223372036854775807)  
uint8	Unsigned integer (0 to 255)   
uint16	Unsigned integer (0 to 65535)  
uint32	Unsigned integer (0 to 4294967295)   
uint64	Unsigned integer (0 to 18446744073709551615)  
float_	Shorthand for float64.  
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa  
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa  
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa  
complex_	Shorthand for complex128.  
complex64	Complex number, represented by two 32-bit floats (real and imaginary components)  
complex128	Complex number, represented by two 64-bit floats (real and imaginary components)  

In [64]:
y = np.float64(1.0)

In [65]:
print(y)

1.0


In [21]:
print(y.astype(int))   

1


In [22]:
print(y.dtype.type)

<class 'numpy.float32'>


#### Creating custom data types with dtype class

In [23]:
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])

In [24]:
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)

In [25]:
print(x)

[('Sarah', [8.0, 7.0]) ('John', [6.0, 7.0])]


In [26]:
print(x.dtype)

[('name', '<U16'), ('grades', '<f8', (2,))]


#### Numpy Operations:
Whenever you perform any operation on numpy array, it get's applied to all the elements. This is called vectorized operations are used for performance enhancements.  


In [27]:
arr=[1,2,3,4]

In [28]:
x=np.array(arr)

In [29]:
print(arr*2)
print(x*2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


#### arange vs linspace

In [66]:
print(np.arange(10,100,5))
print(np.linspace(10,100,5,endpoint=False))

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 10.  28.  46.  64.  82.]


##### Exercise2: What happens if we do linspace with endpoint=False

#### Universal Functions (ufunc)
Universal Functions are compiled functions which operate on ndarrays. They are optimized for performance and are pre-built to handle multi-dimensional inputs. The complete list of ufunc's are at :  
  https://docs.scipy.org/doc/numpy/reference/ufuncs.html  
  Functions which takes one argument are called uniary ufuncs whereas which takes 2 arguments are called binary ufunc's.  

In [31]:
x = np.array([1,2,3])
print(np.square(x)) ## Square is a uniary ufunc

[1 4 9]


Functions which takes one argument are called uniary ufuncs whereas which takes 2 arguments are called binary ufunc's.

In [32]:
y= np.array([1,2,3])
print(np.add(x,y)) ## add is a binary ufunc

[2 4 6]


#### Array Shapes and Broadcasting
In order to operate on multiple arrays, it is necessary that the shape of the arrays match. The simplest case while doing operation is where the input shapes matches.

In [67]:
x=np.array([[1,1,1],[1,1,1]])
print(x)
print(x.shape)

[[1 1 1]
 [1 1 1]]
(2, 3)


In [34]:
y=np.array([[2,2,2],[2,2,2]])
print(y)
print(y.shape)

[[2 2 2]
 [2 2 2]]
(2, 3)


In [35]:
c = x + y
print(c)

[[3 3 3]
 [3 3 3]]


But what happens if x and y are not of same shape ?

In [36]:
z = np.array([[2,2,2]])
print(z)
print(z.shape)

[[2 2 2]]
(1, 3)


In [37]:
print(x+z)

[[3 3 3]
 [3 3 3]]


How did numpy made the operation?   
What happens under the hood is numpy will expand the dimension of z to match that of x and then perform the operation.  
This is called **broadcasting**. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. There are constraints under which python can perform broadcasting though, consider below example where we will reshape z to be of shape (1,2)

In [68]:
z = np.array([[2,2]])
print(z)
print(z.shape)

[[2 2]]
(1, 2)


In [39]:
print(x+z)

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

The rules where a variable can be broadcasted are:  
    1) The arrays all have exactly the same shape.  
    2) The arrays all have the same number of dimensions and the length of each dimensions is either a common length or 1.  
    3)The arrays that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy property 2.  
    *source:*  https://docs.scipy.org/doc/numpy/reference/ufuncs.html  
    https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html

##### Reshaping numpy arrays:

In [40]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
y = x.reshape(5,2)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [42]:
print(y.flatten())

[0 1 2 3 4 5 6 7 8 9]


#### Stacking arrays

In [43]:
x= np.arange(10)
y= np.arange(10)
z = np.vstack([x,y])
print(z)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [44]:
w = np.hstack([x,y])
print(w)

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


#### Boolean Masks

In [77]:
x= np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [98]:
mask = x % 2==0

In [99]:
print(mask)

[ True False  True False  True False  True False  True False]


In [93]:
custom_mask = np.array([False, False, True, True ,True, False, True, True, False, True])

In [94]:
print(x[custom_mask])

[2 3 4 6 7 9]


#### Special functions

In [49]:
print(np.zeros((2,2)))

[[ 0.  0.]
 [ 0.  0.]]


In [95]:
print(np.identity(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [96]:
print(np.full((2,2),7,np.int))

[[7 7]
 [7 7]]


In [52]:
x = np.random.random(24)
x = x.reshape(2,12)
y2 = np.fft.fft2(x) 
print(y2)

[[ 11.34927065+0.j           0.62502230-1.15897746j
   -0.71720271-1.67792659j  -0.82584532-1.27225311j
    0.35555202-0.44042238j  -1.69791781+1.85115788j  -1.11161481+0.j
   -1.69791781-1.85115788j   0.35555202+0.44042238j
   -0.82584532+1.27225311j  -0.71720271+1.67792659j
    0.62502230+1.15897746j]
 [ -0.71989738+0.j          -0.65437086+1.69465147j   1.09735847-0.5345378j
    0.38755282-0.55964413j  -0.82931821-0.28507457j
    0.76380984+0.20239301j  -0.98296748+0.j           0.76380984-0.20239301j
   -0.82931821+0.28507457j   0.38755282+0.55964413j   1.09735847+0.5345378j
   -0.65437086-1.69465147j]]
